export enum StockTypeNatureEnum {
    TRANSFER = 'TRANSFER',
    INSCRIPTION = 'INSCRIPTION',
    REFUND = 'REFUND',
    MUTATION = 'MUTATION',
    DONATION = 'DONATION',
    ATTRIBUTION = 'ATTRIBUTION',
    SUBSCRIPTION = 'SUBSCRIPTION',
    ASSIGNMENT = 'ASSIGNMENT',
    PAYMENT = 'PAYMENT',
    OTHERS = 'OTHERS'
}