export enum StockMoveTypeEnum {
    CAPITAL_ACTION = 'CAPITAL_ACTION',
    ENJOYMENT_ACTION = 'ENJOYMENT_ACTION',
    FOUNDER_SHARE = 'FOUNDER_SHARE',
    BENEFICIARY_SHARE = 'BENEFICIARY_SHARE',
    SOCIAL_SHARE = 'SOCIAL_SHARE',
    BOUND = 'BOUND',
    CONVERTIBLE_BOUND = 'CONVERTIBLE_BOUND'
}