export const countries = [
    {name:'Afghanistan',label:'Afghanistan'},
    {name:'Afrique du Sud',label:'Afrique du Sud'},
    {name:'Albanie',label:'Albanie'},
    {name:'Algérie',label:'Algérie'},
    {name:'Allemagne',label:'Allemagne'},
    {name:'Andorre',label:'Andorre'},
    {name:'Angola',label:'Angola'},
    {name:'Anguilla',label:'Anguilla'},
    {name:'Antarctique',label:'Antarctique'},
    {name:'Antigua-et-Barbuda',label:'Antigua-et-Barbuda'},
    {name:'Arabie saoudite',label:'Arabie saoudite'},
    {name:'Argentine',label:'Argentine'},
    {name:'Arménie',label:'Arménie'},
    {name:'Aruba',label:'Aruba'},
    {name:'Australie',label:'Australie'},
    {name:'Autriche',label:'Autriche'},
    {name:'Azerbaïdjan',label:'Azerbaïdjan'},
    {name:'Bahamas',label:'Bahamas'},
    {name:'Bahreïn',label:'Bahreïn'},
    {name:'Bangladesh',label:'Bangladesh'},
    {name:'Barbade',label:'Barbade'},
    {name:'Belgique',label:'Belgique'},
    {name:'Belize',label:'Belize'},
    {name:'Bénin',label:'Bénin'},
    {name:'Bermudes',label:'Bermudes'},
    {name:'Bhoutan',label:'Bhoutan'},
    {name:'Biélorussie',label:'Biélorussie'},
    {name:'Bolivie',label:'Bolivie'},
    {name:'Bosnie-Herzégovine',label:'Bosnie-Herzégovine'},
    {name:'Botswana',label:'Botswana'},
    {name:'Brésil',label:'Brésil'},
    {name:'Brunéi Darussalam',label:'Brunéi Darussalam'},
    {name:'Bulgarie',label:'Bulgarie'},
    {name:'Burkina Faso',label:'Burkina Faso'},
    {name:'Burundi',label:'Burundi'},
    {name:'Cambodge',label:'Cambodge'},
    {name:'Cameroun',label:'Cameroun'},
    {name:'Canada',label:'Canada'},
    {name:'Cap-Vert',label:'Cap-Vert'},
    {name:'Chili',label:'Chili'},
    {name:'Chine',label:'Chine'},
    {name:'Chypre',label:'Chypre'},
    {name:'Colombie',label:'Colombie'},
    {name:'Comores',label:'Comores'},
    {name:'Congo-Brazzaville',label:'Congo-Brazzaville'},
    {name:'Congo-Kinshasa',label:'Congo-Kinshasa'},
    {name:'Corée du Nord',label:'Corée du Nord'},
    {name:'Corée du Sud',label:'Corée du Sud'},
    {name:'Costa Rica',label:'Costa Rica'},
    {name:'Côte d’Ivoire',label:'Côte d’Ivoire'},
    {name:'Croatie',label:'Croatie'},
    {name:'Cuba',label:'Cuba'},
    {name:'Curaçao',label:'Curaçao'},
    {name:'Danemark',label:'Danemark'},
    {name:'Djibouti',label:'Djibouti'},
    {name:'Dominique',label:'Dominique'},
    {name:'Égypte',label:'Égypte'},
    {name:'Émirats arabes unis',label:'Émirats arabes unis'},
    {name:'Équateur',label:'Équateur'},
    {name:'Érythrée',label:'Érythrée'},
    {name:'Espagne',label:'Espagne'},
    {name:'Estonie',label:'Estonie'},
    {name:'Eswatini',label:'Eswatini'},
    {name:'État de la Cité du Vatican',label:'État de la Cité du Vatican'},
    {name:'États fédérés de Micronésie',label:'États fédérés de Micronésie'},
    {name:'États-Unis',label:'États-Unis'},
    {name:'Éthiopie',label:'Éthiopie'},
    {name:'Fidji',label:'Fidji'},
    {name:'Finlande',label:'Finlande'},
    {name:'France',label:'France'},
    {name:'Gabon',label:'Gabon'},
    {name:'Gambie',label:'Gambie'},
    {name:'Géorgie',label:'Géorgie'},
    {name:'Géorgie du Sud et îles Sandwich du Sud',label:'Géorgie du Sud et îles Sandwich du Sud'},
    {name:'Ghana',label:'Ghana'},
    {name:'Gibraltar',label:'Gibraltar'},
    {name:'Grèce',label:'Grèce'},
    {name:'Grenade',label:'Grenade'},
    {name:'Groenland',label:'Groenland'},
    {name:'Guadeloupe',label:'Guadeloupe'},
    {name:'Guam',label:'Guam'},
    {name:'Guatemala',label:'Guatemala'},
    {name:'Guernesey',label:'Guernesey'},
    {name:'Guinée',label:'Guinée'},
    {name:'Guinée équatoriale',label:'Guinée équatoriale'},
    {name:'Guinée-Bissau',label:'Guinée-Bissau'},
    {name:'Guyana',label:'Guyana'},
    {name:'Guyane française',label:'Guyane française'},
    {name:'Haïti',label:'Haïti'},
    {name:'Honduras',label:'Honduras'},
    {name:'Hongrie',label:'Hongrie'},
    {name:'Île Bouvet',label:'Île Bouvet'},
    {name:'Île Christmas',label:'Île Christmas'},
    {name:'Île de Man',label:'Île de Man'},
    {name:'Île Norfolk',label:'Île Norfolk'},
    {name:'Îles Åland',label:'Îles Åland'},
    {name:'Îles Caïmans',label:'Îles Caïmans'},
    {name:'Îles Cocos',label:'Îles Cocos'},
    {name:'Îles Cook',label:'Îles Cook'},
    {name:'Îles Féroé',label:'Îles Féroé'},
    {name:'Îles Heard et McDonald',label:'Îles Heard et McDonald'},
    {name:'Îles Malouines',label:'Îles Malouines'},
    {name:'Îles Mariannes du Nord',label:'Îles Mariannes du Nord'},
    {name:'Îles Marshall',label:'Îles Marshall'},
    {name:'Îles mineures éloignées des États-Unis',label:'Îles mineures éloignées des États-Unis'},
    {name:'Îles Pitcairn',label:'Îles Pitcairn'},
    {name:'Îles Salomon',label:'Îles Salomon'},
    {name:'Îles Turques-et-Caïques',label:'Îles Turques-et-Caïques'},
    {name:'Îles Vierges britanniques',label:'Îles Vierges britanniques'},
    {name:'Îles Vierges des États-Unis',label:'Îles Vierges des États-Unis'},
    {name:'Inde',label:'Inde'},
    {name:'Indonésie',label:'Indonésie'},
    {name:'Irak',label:'Irak'},
    {name:'Iran',label:'Iran'},
    {name:'Irlande',label:'Irlande'},
    {name:'Islande',label:'Islande'},
    {name:'Israël',label:'Israël'},
    {name:'Italie',label:'Italie'},
    {name:'Jamaïque',label:'Jamaïque'},
    {name:'Japon',label:'Japon'},
    {name:'Jersey',label:'Jersey'},
    {name:'Jordanie',label:'Jordanie'},
    {name:'Kazakhstan',label:'Kazakhstan'},
    {name:'Kenya',label:'Kenya'},
    {name:'Kirghizistan',label:'Kirghizistan'},
    {name:'Kiribati',label:'Kiribati'},
    {name:'Koweït',label:'Koweït'},
    {name:'La Réunion',label:'La Réunion'},
    {name:'Laos',label:'Laos'},
    {name:'Lesotho',label:'Lesotho'},
    {name:'Lettonie',label:'Lettonie'},
    {name:'Liban',label:'Liban'},
    {name:'Libéria',label:'Libéria'},
    {name:'Libye',label:'Libye'},
    {name:'Liechtenstein',label:'Liechtenstein'},
    {name:'Lituanie',label:'Lituanie'},
    {name:'Luxembourg',label:'Luxembourg'},
    {name:'Macédoine du Nord',label:'Macédoine du Nord'},
    {name:'Madagascar',label:'Madagascar'},
    {name:'Malaisie',label:'Malaisie'},
    {name:'Malawi',label:'Malawi'},
    {name:'Maldives',label:'Maldives'},
    {name:'Mali',label:'Mali'},
    {name:'Malte',label:'Malte'},
    {name:'Maroc',label:'Maroc'},
    {name:'Martinique',label:'Martinique'},
    {name:'Maurice',label:'Maurice'},
    {name:'Mauritanie',label:'Mauritanie'},
    {name:'Mayotte',label:'Mayotte'},
    {name:'Mexique',label:'Mexique'},
    {name:'Moldavie',label:'Moldavie'},
    {name:'Monaco',label:'Monaco'},
    {name:'Mongolie',label:'Mongolie'},
    {name:'Monténégro',label:'Monténégro'},
    {name:'Montserrat',label:'Montserrat'},
    {name:'Mozambique',label:'Mozambique'},
    {name:'Myanmar (Birmanie)',label:'Myanmar (Birmanie)'},
    {name:'Namibie',label:'Namibie'},
    {name:'Nauru',label:'Nauru'},
    {name:'Népal',label:'Népal'},
    {name:'Nicaragua',label:'Nicaragua'},
    {name:'Niger',label:'Niger'},
    {name:'Nigéria',label:'Nigéria'},
    {name:'Niue',label:'Niue'},
    {name:'Norvège',label:'Norvège'},
    {name:'Nouvelle-Calédonie',label:'Nouvelle-Calédonie'},
    {name:'Nouvelle-Zélande',label:'Nouvelle-Zélande'},
    {name:'Oman',label:'Oman'},
    {name:'Ouganda',label:'Ouganda'},
    {name:'Ouzbékistan',label:'Ouzbékistan'},
    {name:'Pakistan',label:'Pakistan'},
    {name:'Palaos',label:'Palaos'},
    {name:'Panama',label:'Panama'},
    {name:'Papouasie-Nouvelle-Guinée',label:'Papouasie-Nouvelle-Guinée'},
    {name:'Paraguay',label:'Paraguay'},
    {name:'Pays-Bas',label:'Pays-Bas'},
    {name:'Pays-Bas caribéens',label:'Pays-Bas caribéens'},
    {name:'Pérou',label:'Pérou'},
    {name:'Philippines',label:'Philippines'},
    {name:'Pologne',label:'Pologne'},
    {name:'Polynésie française',label:'Polynésie française'},
    {name:'Porto Rico',label:'Porto Rico'},
    {name:'Portugal',label:'Portugal'},
    {name:'Qatar',label:'Qatar'},
    {name:'R.A.S. chinoise de Hong Kong',label:'R.A.S. chinoise de Hong Kong'},
    {name:'R.A.S. chinoise de Macao',label:'R.A.S. chinoise de Macao'},
    {name:'République centrafricaine',label:'République centrafricaine'},
    {name:'République dominicaine',label:'République dominicaine'},
    {name:'Roumanie',label:'Roumanie'},
    {name:'Royaume-Uni',label:'Royaume-Uni'},
    {name:'Russie',label:'Russie'},
    {name:'Rwanda',label:'Rwanda'},
    {name:'Sahara occidental',label:'Sahara occidental'},
    {name:'Saint-Barthélemy',label:'Saint-Barthélemy'},
    {name:'Saint-Christophe-et-Niévès',label:'Saint-Christophe-et-Niévès'},
    {name:'Saint-Marin',label:'Saint-Marin'},
    {name:'Saint-Martin',label:'Saint-Martin'},
    {name:'Saint-Martin (partie néerlandaise)',label:'Saint-Martin (partie néerlandaise)'},
    {name:'Saint-Pierre-et-Miquelon',label:'Saint-Pierre-et-Miquelon'},
    {name:'Saint-Vincent-et-les-Grenadines',label:'Saint-Vincent-et-les-Grenadines'},
    {name:'Sainte-Hélène',label:'Sainte-Hélène'},
    {name:'Sainte-Lucie',label:'Sainte-Lucie'},
    {name:'Salvador',label:'Salvador'},
    {name:'Samoa',label:'Samoa'},
    {name:'Samoa américaines',label:'Samoa américaines'},
    {name:'Sao Tomé-et-Principe',label:'Sao Tomé-et-Principe'},
    {name:'Sénégal',label:'Sénégal'},
    {name:'Serbie',label:'Serbie'},
    {name:'Seychelles',label:'Seychelles'},
    {name:'Sierra Leone',label:'Sierra Leone'},
    {name:'Singapour',label:'Singapour'},
    {name:'Slovaquie',label:'Slovaquie'},
    {name:'Slovénie',label:'Slovénie'},
    {name:'Somalie',label:'Somalie'},
    {name:'Soudan',label:'Soudan'},
    {name:'Soudan du Sud',label:'Soudan du Sud'},
    {name:'Sri Lanka',label:'Sri Lanka'},
    {name:'Suède',label:'Suède'},
    {name:'Suisse',label:'Suisse'},
    {name:'Suriname',label:'Suriname'},
    {name:'Svalbard et Jan Mayen',label:'Svalbard et Jan Mayen'},
    {name:'Syrie',label:'Syrie'},
    {name:'Tadjikistan',label:'Tadjikistan'},
    {name:'Taïwan',label:'Taïwan'},
    {name:'Tanzanie',label:'Tanzanie'},
    {name:'Tchad',label:'Tchad'},
    {name:'Tchéquie',label:'Tchéquie'},
    {name:'Terres australes françaises',label:'Terres australes françaises'},
    {name:'Territoire britannique de l’océan Indien',label:'Territoire britannique de l’océan Indien'},
    {name:'Territoires palestiniens',label:'Territoires palestiniens'},
    {name:'Thaïlande',label:'Thaïlande'},
    {name:'Timor oriental',label:'Timor oriental'},
    {name:'Togo',label:'Togo'},
    {name:'Tokelau',label:'Tokelau'},
    {name:'Tonga',label:'Tonga'},
    {name:'Trinité-et-Tobago',label:'Trinité-et-Tobago'},
    {name:'Tunisie',label:'Tunisie'},
    {name:'Turkménistan',label:'Turkménistan'},
    {name:'Turquie',label:'Turquie'},
    {name:'Tuvalu',label:'Tuvalu'},
    {name:'Ukraine',label:'Ukraine'},
    {name:'Uruguay',label:'Uruguay'},
    {name:'Vanuatu',label:'Vanuatu'},
    {name:'Venezuela',label:'Venezuela'},
    {name:'Vietnam',label:'Vietnam'},
    {name:'Wallis-et-Futuna',label:'Wallis-et-Futuna'},
    {name:'Yémen',label:'Yémen'},
    {name:'Zambie',label:'Zambie'},
    {name:'Zimbabwe',label:'Zimbabwe'},
];