-- Create table t_shareholder
create table if not exists t_shareholder
(
    c_id                   uuid                        not null,
    c_tenant_id            uuid,
    c_created_at           timestamp with time zone not null,
    c_updated_at           timestamp with time zone,
    c_name                 varchar(128)                not null,
    c_administrator        varchar(128),
    c_account_number       varchar(64)                 not null,
    c_bank_account_number  varchar(64),
    c_email                varchar(128),
    c_phone                varchar(32),
    c_account_type         varchar(32)                 not null,
    c_shareholder_type     varchar(32)                 not null,
    c_city                 varchar(64),
    c_zip_code             varchar(64),
    c_tax_residence        varchar(64)                 not null,
    c_initial_balance      numeric(38,2)               not null,
    c_created_date         timestamp with time zone not null,
    c_active               boolean                     not null,
    c_representative_name  varchar(128)                not null,
    c_representative_email varchar(128),
    c_representative_phone varchar(32),
    c_successor_name       varchar(128),
    c_successor_email      varchar(128),
    c_successor_phone      varchar(32),
    constraint pk_t_shareholder primary key (c_id),
    constraint Uk_t_shareholder_c_account_number unique (c_account_number),
    constraint Uk_t_shareholder_c_bank_account_number unique (c_bank_account_number),
    constraint Uk_t_shareholder_c_email unique (c_email),
    constraint Uk_t_shareholder_c_phone unique (c_phone),
    constraint Uk_t_shareholder_c_representative_email unique (c_representative_email),
    constraint Uk_t_shareholder_c_representative_phone unique (c_representative_phone),
    constraint Uk_t_shareholder_c_successor_email unique (c_successor_email),
    constraint Uk_t_shareholder_c_successor_phone unique (c_successor_phone)
);
