-- Create table t_company
create table if not exists t_company (
    c_id uuid not null ,
    c_created_at timestamp with time zone not null ,
    c_updated_at timestamp with time zone,
    c_company_name varchar(64) not null ,
    c_company_manager_name varchar(64) not null ,
    c_licence varchar(64) not null ,
    c_legal_form varchar(64) not null ,
    c_address_street varchar(128) ,
    c_address_city varchar(64) not null ,
    c_address_zip_code varchar(16) not null ,
    c_address_country varchar(64) not null ,
    c_contact_phone varchar(32) ,
    c_contact_fax varchar(32) ,
    c_contact_email varchar(128) not null ,
    c_contact_name varchar(64) not null ,
    c_activity varchar(128) ,
    c_registration_number varchar(32) ,
    c_website_url varchar(64) ,
    c_isin_code varchar(32) ,
    c_tax_number varchar(32) ,
    c_logo_filename varchar(512) ,
    c_stamp_filename varchar(512) ,
    c_gross_dividend_stock_unit numeric(38,2) ,
    c_nominal_value numeric(38,2) ,
    c_stock_quantity  numeric(38,0) ,
    c_active boolean not null ,
    c_certificate_template_id uuid ,
    c_created_date timestamp with time zone not null ,
    constraint Pk_t_company_c_id primary key (c_id),
    constraint Uk_t_company_c_company_name unique (c_company_name),
    constraint Uk_t_company_c_tax_number unique (c_tax_number),
    constraint Uk_t_company_c_isin_code unique (c_isin_code),
    constraint Uk_t_company_c_website_url unique (c_website_url),
    constraint Uk_t_company_c_registration_number unique (c_registration_number),
    constraint Uk_t_company_c_contact_email unique (c_contact_email),
    constraint Uk_t_company_c_contact_fax unique (c_contact_fax),
    constraint Uk_t_company_c_contact_phone unique (c_contact_phone),
    constraint Fk_t_company_c_certificate_template_id foreign key (c_certificate_template_id) references t_certificate_template (c_id)
);